### PR TITLE
Add an up to date RFC.bib

### PR DESCRIPTION
**Pull request by N0taN3rd**
This is the wsdl thesis repo is it not :wink:

### CODE REVIEW

**Comment by ibnesayeed** [comment]
No need to pollute with unnecessary crap. ;-)

**Comment by machawk1** [comment]
@N0taN3rd The RFC .bib would be useful but is quite verbose for this repo, which I think @ibnesayeed wants to serve as a MWE. Maybe put it in a separate repo under the oduwsdl org then we can instruct via the README in this repo additional options to pull this file as well for a standard reference format.

**Comment by ibnesayeed** [comment]
A note in the README that points to something like http://project.hupili.net/rfc.bib/ would be helpful for people who really want to cite a lot of RFCs. However, we would perhaps fork the corresponding repo and change the template to generate bib records the way @phonedude likes them to be.

**Comment by ibnesayeed** [comment]
Verbosity of the `rfc.bib` file is an issue, but it is not the only issue why I would suggest not to keep it here. Currently, we supply a very simple and small `ref.bib` file, from where new users can build upon as they need. Including multiple bib files means more documentation and more confusing files. The most recent RFC as of now is 8255, which means, just a few lines per RFC would create several thousands of lines, most of which would be of no good use for many.

**Pull request closed without merging**
